//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNRParser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airport
    {
        public int ID { get; set; }
        public string CityCode { get; set; }
        public string CityDescription { get; set; }
        public string Airport1 { get; set; }
    }
}
